version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: healthcare_backend
    ports:
      - "8000:8000"
    volumes:
      - .:/app

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.streamlit
    container_name: healthcare_frontend
    ports:
      - "8501:8501"
    depends_on:
      - backend
    volumes:
      - .:/app